name:                mcc
version:             0.1.0.0
github:              "zachary0kent/mcc"
license:             BSD3
author:              "Zachary Kent"
maintainer:          "zak33@cornell.edu"
copyright:           "2022 Zachary Kent"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/mcc#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - array
  - containers
  - text
  - string-conversions
  - directory
  - process
  - unix
  - filepath
  - bytestring
  - prettyprinter
  - pretty-simple
  - llvm-hs-pure >= 9 && < 10
  - llvm-hs-pretty >= 0.9 && < 1
  - attoparsec

library:
  source-dirs: src

executables:
  mcc-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mcc

tests:
  mcc-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mcc

default-extensions: OverloadedStrings, LambdaCase
build-tools: 
- alex
- happy
